<?php

function legacy_code_example_menu() {
  $items['node/%/repos'] = array(
    'title' => 'List of repos for this project',
    'page callback' => 'legacy_code_example_show_repos',
    'access callback' => TRUE,
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Show all repos for for GitHub users whose name match the node title.
 */
function legacy_code_example_show_repos() {
  $displayer = new LegacyCodeExample();
  return $displayer->result();
}
